---
title: "Generative Art"
author: "Nick Soares"
format: html
editor: visual
---

```{r}
#| warning: false
#| echo: false
#| label: load-packages

library(tidyverse)
library(ggthemes)
library(scales)
library(ambient)
```

## Art Piece 1

```{r}
#| warning: false
#| label: building-art-one

#using a phytoplankton monitoring time series from Morro Bay
hab <- read.csv("data/MBF_upload.csv")

#modifying and overlaying data on a single plot
hab |>
  ggplot() +
  geom_point(aes(Day.of.Year..1.365., 
             log10(Total.Phytoplankton..cells.L.), 
             colour = Day.of.Year..1.365., 
             size = Avg.Chloro..mg.m3./2),
             show.legend = FALSE) +
  geom_point(aes(abs(366-Day.of.Year..1.365.), 
             log(Total.Phytoplankton..cells.L.), 
             colour = Day.of.Year..1.365., 
             size = Avg.Chloro..mg.m3.),
             show.legend = FALSE) +
  geom_bar(aes(Day.of.Year..1.365., 
              log10(Akashiwo.sanguinea..cells.L.), 
              colour  = Temp..deg.C.*20),
           stat = "identity", 
           show.legend = FALSE) +
  geom_bar(aes(Day.of.Year..1.365., 
              log10(Pseudo.nitzschia.seriata.group..cells.L.), 
              colour  = Temp..deg.C.*10),
           stat = "identity", 
           show.legend = FALSE) +
  coord_polar() + 
  theme_void() +
  scale_color_viridis_c()

```

## Art Piece 2

```{r}
#| warning: false
#| label: building-art-two

#generate color palettes
sample_canva <- function(seed = NULL) {
  if(!is.null(seed)) set.seed(seed)
  sample(ggthemes::canva_palettes, 1)[[1]]
}

#create a canvas
x_coords <- seq(from = 0, to = 1, length.out = 800)
y_coords <- seq(from = 0, to = 1, length.out = 800)
canvas <- long_grid(x = x_coords, y = y_coords) 

#add some generated "paint" to the canvas
canvas <- canvas |>
  mutate(paint = fracture(
            noise = gen_simplex,
            x = x,
            y = y,
            octaves = 20,
            fractal = fbm,
            seed = 29))

#putting it all together with a generated color palette
art <- ggplot(canvas, aes(x, y, fill = paint)) + 
  geom_raster(show.legend = FALSE) +
  theme_void() +
  coord_equal() +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_gradientn(colours = sample_canva(seed = 42))
art

#defining the shape of a nonagon
theta <- (0:9) * pi / 4.5
nonagon <- tibble(
  x = sin(theta),
  y = cos(theta)
)
nonagon_scale <- nonagon %>%
  mutate(x_scale = x/4, 
         y_scale = y/4)

#plotting nonagon
pic <- ggplot(nonagon) +
  geom_polygon(aes(x, y), 
               colour = "black", 
               fill = NA, 
               show.legend = FALSE) +
  geom_polygon(aes(x-0.5, y-0.5), 
               colour = "black", 
               fill = NA, 
               show.legend = FALSE) +
    geom_polygon(aes(x+0.5, y+0.5), 
               colour = "black", 
               fill = NA, 
               show.legend = FALSE) +
  coord_equal() + 
  theme_void()
pic

#putting them together
ggplot() +
  geom_raster(data = canvas, 
              aes(x, y, fill = paint), 
              show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_gradientn(colours = sample_canva(seed = 42)) +
  geom_polygon(data = nonagon_scale,
               aes(x_scale, y_scale), 
               colour = "white", 
               fill = NA, 
               show.legend = FALSE) +
  geom_polygon(data = nonagon_scale,
               aes(x_scale-0.05, y_scale-0.05), 
               colour = "black", 
               fill = NA, 
               show.legend = FALSE) +
  geom_polygon(data = nonagon_scale,
               aes(x_scale+0.05, y_scale+0.05), 
               colour = "black", 
               fill = NA, 
               show.legend = FALSE) +
  coord_equal() + 
  theme_void()

```
